version: 2.1

executors:
  docker-executor:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester

workflows:
  version: 2
  commit:
    jobs:
      - ensure_env:
          context: circleci-user
      - fake_test:
          context: circleci-user
          requires:
            - ensure_env
      - fake_deploy:
          context: circleci-user
          requires:
            - ensure_env
          filters:
            branches:
              only: master
      - build:
          requires:
            - ensure_env
            - fake_test

jobs:
  ensure_env:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: 'Setup Virtual Env'
          command: |
            python3 -m venv /usr/local/share/virtualenvs/tap-shiphero
            source /usr/local/share/virtualenvs/tap-shiphero/bin/activate
            pip install -U pip setuptools
            pip install .[test]
      - persist_to_workspace:
          root: /usr/local/share/virtualenvs
          paths:
            - tap-shiphero
  fake_test:
    executor: docker-executor
    steps:
      - run: echo "Test succeeded"
  fake_deploy:
    executor: docker-executor
    steps:
      - checkout
      - run: python3 -m venv /usr/local/share/virtualenvs/tap-shiphero
      - run: source /usr/local/share/virtualenvs/tap-shiphero/bin/activate
      - run:
          name: 'Create git tag'
          command: |
            version=$(python setup.py --version)
            git config user.email "stitchintegrationdev@talend.com"
            git config user.name "Stitch IntegrationDev"
            git tag -a v"${version}" -m "version ${version}"
            git push --tags
      - run:
          name: 'Build and Upload'
          command: |
            pip install twine
            python setup.py sdist --dist-dir dist
            twine upload --repository testpypi --username $PYPI_USERNAME --password $PYPI_PASSWORD ./dist/*
